apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true

  opensearch.yaml: |
    apiVersion: 1
    datasources:
      - name: OpenSearch
        type: opensearch
        access: proxy
        url: https://opensearch:9200
        basicAuth: true
        basicAuthUser: admin
        basicAuthPassword: admin
